revise env vars

diff --git a/bin/talk2text-nvim b/bin/talk2text-nvim
--- a/bin/talk2text-nvim
+++ b/bin/talk2text-nvim
@@ -6,8 +6,8 @@ readonly TARGET_NAME="nvim-target"
 readonly DEFAULT_TARGET_NAME="default-nvim-target"
 readonly REMOTE_OK="talk2text-ok"
 
-readonly NOTIFY_CMD=${TALK2TEXT_NVIM_NOTIFY_CMD-'notify-send -a talk2text -u normal -t 5000 Talk2text "$@"'}
-readonly CLIENT_CMD=${TALK2TEXT_NVIM_CLIENT_CMD-'nvim "$@"'}
+readonly NOTIFY_CMD=${TALK2TEXT_NVIM_NOTIFY_CMD-'notify-send -a talk2text -u normal -t 5000 Talk2text'}
+readonly NVIM_CMD=${TALK2TEXT_NVIM_CMD-nvim}
 readonly TERMINAL_CMD=${TALK2TEXT_NVIM_TERMINAL_CMD-}
 readonly FOCUS_CMD=${TALK2TEXT_NVIM_FOCUS_CMD-}
 
@@ -36,7 +36,11 @@ path_exists() {
 run_hook() {
   local code="$1"
   shift
-  sh -c "$code" talk2text-nvim-hook "$@"
+  sh -c "$code"' "$@"' talk2text-nvim-hook "$@"
+}
+
+run_nvim() {
+  run_hook "$NVIM_CMD" "$@"
 }
 
 notify() {
@@ -119,7 +123,7 @@ encode_lua_bytes() {
 
 probe_server() {
   local socket="$1"
-  run_hook "$CLIENT_CMD" --server "$socket" --remote-expr 1 2>/dev/null
+  run_nvim --server "$socket" --remote-expr 1 2>/dev/null
 }
 
 load_in_server() {
@@ -127,7 +131,7 @@ load_in_server() {
   encode_lua_bytes "$TRANSCRIPT_PATH"
   local expression="luaeval('require(\"talk2text\")._remote_load(\"$LUA_BYTES\")')"
   local response
-  response=$(run_hook "$CLIENT_CMD" --server "$socket" --remote-expr "$expression") || return 1
+  response=$(run_nvim --server "$socket" --remote-expr "$expression") || return 1
   [[ $response == "$REMOTE_OK" ]]
 }
 
@@ -163,12 +167,12 @@ start_default_editor() {
 
   encode_lua_bytes "$TRANSCRIPT_PATH"
   local startup="lua require(\"talk2text\")._default_start(\"$LUA_BYTES\")"
-  run_hook "$TERMINAL_CMD" -c "$startup"
+  run_hook "$TERMINAL_CMD $NVIM_CMD" -c "$startup"
 }
 
 handle_text() {
-  if [[ -z $CLIENT_CMD ]]; then
-    fail "TALK2TEXT_NVIM_CLIENT_CMD is required for text delivery"
+  if [[ -z $NVIM_CMD ]]; then
+    fail "TALK2TEXT_NVIM_CMD is required for handling transcripts"
     return 1
   fi
   if [[ ! -f $TRANSCRIPT_PATH || ! -r $TRANSCRIPT_PATH ]]; then
